plugins {
    id 'com.android.application'
}

android {
    namespace 'com.devlomi.watchface.watchface'
    compileSdk 35

    defaultConfig {
        applicationId "com.devlomi.prayerwatchface.v2"
        minSdk 34
        targetSdk 35
        versionCode 10
        versionName "1.0.1"

    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

