plugins {
    id 'com.android.application'
}

android {
    namespace 'com.devlomi.prayerwatchface.v2.analog'
    compileSdk 34

    defaultConfig {
        applicationId "com.devlomi.prayerwatchface.v2.analog"
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

