package com.devlomi.shared.constants

object ConfigKeys {
    const val CALCULATION_METHOD = "calc-method"
    const val ASR_CALC_MADHAB = "asr-calc-method"
    const val LAT = "lat"
    const val LNG = "lng"
    const val BACKGROUND_COLOR = "bgcolor"
    const val BACKGROUND_COLOR_BOTTOM_PART = "bgcolorbpart"
    const val FOREGROUND_COLOR = "fgcolor"
    const val FOREGROUND_COLOR_BOTTOM_PART = "fgcolorbpart"
    const val TWENTY_FOUR_HOURS = "24h"
    const val HIJRI_OFFSET = "hijriOffset"
    const val FAJR_OFFSET = "fajrOffset"
    const val SHUROOQ_OFFSET = "shurooqOffset"
    const val DHUHR_OFFSET = "dhuhrOffset"
    const val ASR_OFFSET = "asrOffset"
    const val MAGHRIB_OFFSET = "maghribOffset"
    const val ISHA_OFFSET = "ishaOffset"
    const val DAYLIGHT_SAVING_OFFSET = "daylightOffset"
    const val ELAPSED_TIME_ENABLED = "elapsedTimeEnabled"
    const val ELAPSED_TIME_MINUTES = "elapsedMinutes"
    const val SHOW_PRAYER_TIMES_ON_CLICK = "showPrayerTimesOnClick"
    const val LOCALE_TYPE = "localeType"
    const val NOTIFICATIONS_ENABLED = "notificationsEnabled"
    const val WALLPAPER = "wallpaper"
    const val REMOVE_BOTTOM_PART = "remove-bpart"
    const val FONT_SIZE = "font-size"
    const val CUSTOM_WALLPAPER_ENABLED = "custom-wpper-enabled"
    const val WALLPAPER_OPACITY = "wallpaperOpacity"
    const val COMPLICATIONS_ENABLED = "complicationsEnabled"
    const val LEFT_COMPLICATION_ENABLED = "leftComplicationEnabled"
    const val RIGHT_COMPLICATION_ENABLED = "rightComplicationEnabled"
    const val PROGRESS_ENABLED = "progressEnabled"
    const val PROGRESS_COLOR = "progressColor"
    const val HAND_PRIMARY_COLOR = "handPrimaryColor"
    const val HAND_SECONDARY_COLOR = "handSecondaryColor"
    const val HOUR_MARKER_COLOR = "hourMarkerColor"
    const val TAP_TYPE = "tapType"
    const val CURRENT_WATCHFACE_ID = "currentWatchFaceId"

}